#import <AppKit/AppKit.h>
#import <objc/runtime.h>
#import <stdio.h>

// Go side of the bridge (generated by cgo from //export).
extern void roammingReopenActivated(void);

static BOOL roamReopenImp(id self, SEL _cmd, NSApplication *app,
                          BOOL hasVisibleWindows) {
    roammingReopenActivated();
    return YES;
}

// roamAttachReopen adds the reopen hook to glfw's application delegate
// by name, at runtime. This file holds no static reference to the
// class: nothing for the linker or dyld to resolve, and if glfw ever
// renames the class — or it is absent, as in this package's standalone
// test binary — the lookup returns nil and the app keeps working, just
// without the reopen restore.
void roamAttachReopen(void) {
    Class cls = objc_getClass("GLFWApplicationDelegate");
    if (cls == Nil) {
        return;
    }
    SEL sel = @selector(applicationShouldHandleReopen:);
    char types[32]; // return, id, SEL, NSApplication *, BOOL
    snprintf(types, sizeof types, "%s@:%s%s",
             @encode(BOOL), @encode(id), @encode(BOOL));
    class_addMethod(cls, sel, (IMP)roamReopenImp, types);
    // A NO return means glfw implements the method already (or we
    // attached earlier); whatever is there stays untouched.
}
