#import <AppKit/AppKit.h>

// Go side of the bridge (generated by cgo from //export).
extern void roammingReopenActivated(void);

// GLFW's Cocoa driver defines its application delegate under this
// name (cocoa_init.m) and installs it with [NSApp setDelegate:]. The
// category below adds the reopen hook without patching glfw. Should a
// future glfw rename the class, the category simply never attaches
// and the app keeps today's behavior — no crash, just no restore.
@interface GLFWApplicationDelegate : NSObject
@end

@implementation GLFWApplicationDelegate (RoamReopen)

// Re-opening the running bundle lands here on the running instance.
// Returning YES reports the event as handled.
- (BOOL)applicationShouldHandleReopen:(NSApplication *)theApplication
                    hasVisibleWindows:(BOOL)flag {
    roammingReopenActivated();
    return YES;
}

@end
